name: cijepise_flutter_2
description: Cijepi se mobilna aplikacija.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.2
  http: ^0.13.4
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.12
  intl: ^0.17.0
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.6
  flutter_local_notifications: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  json_serializable: ^6.1.4
  build_runner: ^2.1.7

flutter:

  uses-material-design: true

  fonts:
    - family: UniSans
      fonts:
        - asset: assets/fonts/uni_sans_regular.ttf

  assets:
    - assets/images/
    - assets/icons/
    - lib/data/gradovi.json
